### ISSUE TITLE
[Bug] Stucked at step 3 due to axios dependency

### ISSUE THREAD

**Issue by JoeChrys** [skills/secure-repository-supply-chain#18]
### Summary

Due to a new vulnerability for axios 0.21.2, Depeandabot creates a PR "Bump axios from 0.21.1 to 1.6.0 in /code/src/AttendeeSite" indtead of "Bump axios from 0.21.1 to 0.21.2 in /code/src/AttendeeSite". As a result GH Actions cant proceed to the next step.

### How to reproduce

Just follow the step of the tutorial

**Comment by rsese** [comment]
Should be fixed by https://github.com/skills/secure-repository-supply-chain/pull/17
