### ISSUE TITLE
[Bug] Axios dependency version check fails in step 3 of the workflow.

### ISSUE THREAD

**Issue by thisisbramiller** [skills/secure-repository-supply-chain#19]
Summary
This issue has been reoccurring. Due to a new vulnerability for axios, Depeandabot creates a PR "Bump axios from 0.21.1 to 0.28.0 in /code/src/AttendeeSite" indtead of "Bump axios from 0.21.1 to 0.21.2 in /code/src/AttendeeSite". As a result GH Actions cant proceed to the next step.

Instead of hardcoding the value, might the version check validate against a regex or range?

How to reproduce
Just follow the step of the tutorial

**Comment by sinsukehlab** [comment]
Regex suggestion (need further escaping in the workflow)

For package.json: `"axios": "\^(?!0\.21\.1)(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?"`
For package-lock.json: `axios-(?!0\.21\.1)(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?`

**Comment by sinsukehlab** [comment]
Need `--perl-regexp`
`search: "\"axios\":\ \"\\^(?!0\\.21\\.1)(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\""`
`search: "axios-(?!0\\.21\\.1)(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\""`

**Comment by ineffyble** [comment]
Same problem here.
